### ISSUE TITLE
Does not support markdown inside markdown tables

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/fiddly#4]
If a Readme has https://github.com/kentcdodds/all-contributors it doesn't look okay, the tables are all screwed up

oh no 😭

Example: https://5c2381e1724ef9d69ec7827f--fiddly.netlify.com/

Repo: https://github.com/gnapse/jest-dom

**Comment by SaraVieira** [comment]
All Contribs list always starts with:
```
<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore -->
```

And ends with:

```
<!-- ALL-CONTRIBUTORS-LIST:END -->
```

So this could help in the styling of this part

**Comment by Dan503** [comment]
The actual issue seems to be that fiddly can't read markdown inside markdown tables properly.

It not rendering the "all contributors" section on your specific readme is more like a simptom/use-case than the core issue.

I would suggest renaming the issue to:
"Does not support markdown inside markdown tables".

**Comment by SaraVieira** [comment]
That is true! Changed the title

**Comment by SaraVieira** [comment]
Fixed by: https://github.com/SaraVieira/fiddly/commit/5cbed2e605f97a13b6bdf907d0c00eaa1d25e517
